/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aaqib
 */
public class Screen extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        withdraw = new javax.swing.JButton();
        billpay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        withdrawlable = new javax.swing.JLabel();
        inquerylable = new javax.swing.JLabel();
        Transferlable = new javax.swing.JLabel();
        billplable = new javax.swing.JLabel();
        enterpin = new javax.swing.JLabel();
        Pinfield = new javax.swing.JTextField();
        pincontinue = new javax.swing.JButton();
        inquery = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        cardNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        three = new javax.swing.JButton();
        one = new javax.swing.JButton();
        six = new javax.swing.JButton();
        two = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        cancle = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        enterbutton = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        bill = new javax.swing.JPanel();
        bill_lable = new javax.swing.JLabel();
        billno_field = new javax.swing.JTextField();
        billtype_lable = new javax.swing.JLabel();
        cBox_bill = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        billText = new javax.swing.JTextArea();
        receipt_bill = new javax.swing.JButton();
        billtype_lable1 = new javax.swing.JLabel();
        bill_amount_field = new javax.swing.JTextField();
        withdrawpanel = new javax.swing.JPanel();
        amountlable_withdraw = new javax.swing.JLabel();
        with_draw_amount_field = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_withdraw = new javax.swing.JTextArea();
        receiptWithdraw = new javax.swing.JButton();
        reset_withdraw = new javax.swing.JButton();
        exit_withdraw = new javax.swing.JButton();
        Transfer = new javax.swing.JPanel();
        transfer_acount_field = new javax.swing.JTextField();
        accountnumberlable_transfer = new javax.swing.JLabel();
        amountlable_transfer = new javax.swing.JLabel();
        transfer_amount_field = new javax.swing.JTextField();
        receipt_transfer = new javax.swing.JButton();
        reset_transfer = new javax.swing.JButton();
        exit_Transfer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        transferfield = new javax.swing.JTextArea();
        Inquery = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        inqueryText = new javax.swing.JTextArea();
        userAccount = new javax.swing.JLabel();
        userAmount = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        actNb = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(82, 190, 128));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        withdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/lArrow.png"))); // NOI18N
        withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawActionPerformed(evt);
            }
        });
        jPanel1.add(withdraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 50));

        billpay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/lArrow.png"))); // NOI18N
        billpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billpayActionPerformed(evt);
            }
        });
        jPanel1.add(billpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 100, 60));

        jPanel2.setBackground(new java.awt.Color(82, 190, 128));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setForeground(new java.awt.Color(0, 102, 102));

        withdrawlable.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        withdrawlable.setText("WithDraw");

        inquerylable.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        inquerylable.setText("Inquery");

        Transferlable.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        Transferlable.setText("Transfer");

        billplable.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        billplable.setText("Bill Pay");

        enterpin.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        enterpin.setText("Enter Pin");

        pincontinue.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        pincontinue.setText("Continue");
        pincontinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincontinueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inquerylable, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Transferlable, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(pincontinue)
                                    .addComponent(Pinfield, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enterpin, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(withdrawlable, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(billplable, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(withdrawlable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inquerylable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pinfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Transferlable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(billplable, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pincontinue))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 310, 240));

        inquery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/lArrow.png"))); // NOI18N
        inquery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inqueryActionPerformed(evt);
            }
        });
        jPanel1.add(inquery, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 60));

        transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/lArrow.png"))); // NOI18N
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });
        jPanel1.add(transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 60));

        cardNumber.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        cardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberActionPerformed(evt);
            }
        });
        jPanel1.add(cardNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 10, 270, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/niyamakata.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 270, 213));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 720, 250));

        jPanel4.setBackground(new java.awt.Color(82, 190, 128));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        four.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/four.png"))); // NOI18N
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/five.png"))); // NOI18N
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        three.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/three.png"))); // NOI18N
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        one.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/one.png"))); // NOI18N
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        six.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/six.png"))); // NOI18N
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        two.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/two.png"))); // NOI18N
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        seven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/seven.png"))); // NOI18N
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/eight.png"))); // NOI18N
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/nine.png"))); // NOI18N
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        zero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/zero.png"))); // NOI18N
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/empty.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/empty.png"))); // NOI18N

        cancle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/cancel.png"))); // NOI18N
        cancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleActionPerformed(evt);
            }
        });

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/clear.png"))); // NOI18N
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        enterbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/enter.png"))); // NOI18N
        enterbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterbuttonActionPerformed(evt);
            }
        });

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atm/empty.png"))); // NOI18N
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enterbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eight, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seven, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(enterbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 430, 340));

        bill.setBackground(new java.awt.Color(82, 190, 128));

        bill_lable.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        bill_lable.setText("Bill Number");

        billno_field.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        billtype_lable.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        billtype_lable.setText("Bill Type");

        cBox_bill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Electricity", "Gass", "Internet", "Trafic Challan" }));

        billText.setColumns(20);
        billText.setRows(5);
        jScrollPane3.setViewportView(billText);

        receipt_bill.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        receipt_bill.setText("Receipt");
        receipt_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receipt_billActionPerformed(evt);
            }
        });

        billtype_lable1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        billtype_lable1.setText("Amount");

        bill_amount_field.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        javax.swing.GroupLayout billLayout = new javax.swing.GroupLayout(bill);
        bill.setLayout(billLayout);
        billLayout.setHorizontalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(receipt_bill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billLayout.createSequentialGroup()
                        .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(billLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, billLayout.createSequentialGroup()
                                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bill_lable)
                                    .addComponent(billtype_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(billtype_lable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(billno_field)
                                    .addComponent(cBox_bill, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bill_amount_field))))
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        billLayout.setVerticalGroup(
            billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bill_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(billno_field, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(billtype_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBox_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(billtype_lable1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(bill_amount_field))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receipt_bill))
        );

        getContentPane().add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 290, 340));

        withdrawpanel.setBackground(new java.awt.Color(82, 190, 128));
        withdrawpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        amountlable_withdraw.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        amountlable_withdraw.setText("Enter Amount ");

        with_draw_amount_field.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        with_draw_amount_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        with_draw_amount_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                with_draw_amount_fieldKeyTyped(evt);
            }
        });

        text_withdraw.setColumns(20);
        text_withdraw.setRows(5);
        jScrollPane1.setViewportView(text_withdraw);

        receiptWithdraw.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        receiptWithdraw.setText("Receipt");
        receiptWithdraw.setBorder(null);
        receiptWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptWithdrawActionPerformed(evt);
            }
        });

        reset_withdraw.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        reset_withdraw.setText("Reset");
        reset_withdraw.setBorder(null);
        reset_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_withdrawActionPerformed(evt);
            }
        });

        exit_withdraw.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        exit_withdraw.setText("Exit");
        exit_withdraw.setBorder(null);
        exit_withdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_withdrawActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdrawpanelLayout = new javax.swing.GroupLayout(withdrawpanel);
        withdrawpanel.setLayout(withdrawpanelLayout);
        withdrawpanelLayout.setHorizontalGroup(
            withdrawpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(withdrawpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, withdrawpanelLayout.createSequentialGroup()
                        .addComponent(amountlable_withdraw)
                        .addGap(18, 18, 18)
                        .addComponent(with_draw_amount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(withdrawpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiptWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(reset_withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit_withdraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        withdrawpanelLayout.setVerticalGroup(
            withdrawpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(withdrawpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountlable_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(with_draw_amount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(withdrawpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawpanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(receiptWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(reset_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exit_withdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(withdrawpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        getContentPane().add(withdrawpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 490, 250));

        Transfer.setBackground(new java.awt.Color(82, 190, 128));
        Transfer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        transfer_acount_field.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        transfer_acount_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        accountnumberlable_transfer.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        accountnumberlable_transfer.setText("Account Number ");

        amountlable_transfer.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        amountlable_transfer.setText("Amount ");

        transfer_amount_field.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        transfer_amount_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        receipt_transfer.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        receipt_transfer.setText("Receipt");
        receipt_transfer.setBorder(null);
        receipt_transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receipt_transferActionPerformed(evt);
            }
        });

        reset_transfer.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        reset_transfer.setText("Reset");
        reset_transfer.setBorder(null);
        reset_transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_transferActionPerformed(evt);
            }
        });

        exit_Transfer.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        exit_Transfer.setText("Exit");
        exit_Transfer.setBorder(null);
        exit_Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_TransferActionPerformed(evt);
            }
        });

        transferfield.setColumns(20);
        transferfield.setRows(5);
        jScrollPane2.setViewportView(transferfield);

        javax.swing.GroupLayout TransferLayout = new javax.swing.GroupLayout(Transfer);
        Transfer.setLayout(TransferLayout);
        TransferLayout.setHorizontalGroup(
            TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransferLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reset_transfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(exit_Transfer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TransferLayout.createSequentialGroup()
                        .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TransferLayout.createSequentialGroup()
                                .addComponent(amountlable_transfer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(transfer_amount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(receipt_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TransferLayout.createSequentialGroup()
                                .addComponent(accountnumberlable_transfer)
                                .addGap(18, 18, 18)
                                .addComponent(transfer_acount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        TransferLayout.setVerticalGroup(
            TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransferLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountnumberlable_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfer_acount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountlable_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transfer_amount_field, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(receipt_transfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(TransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TransferLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reset_transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exit_Transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(TransferLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(Transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 490, 340));

        Inquery.setBackground(new java.awt.Color(82, 190, 128));
        Inquery.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 3));
        Inquery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inqueryText.setColumns(20);
        inqueryText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        inqueryText.setRows(5);
        jScrollPane4.setViewportView(inqueryText);

        Inquery.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 9, 1172, 41));

        userAccount.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        userAccount.setText("Account Number:");
        Inquery.add(userAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 56, 162, 40));

        userAmount.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        userAmount.setText("Current Balance:");
        Inquery.add(userAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 162, 49));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        Inquery.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2125, 49, -1, -1));

        actNb.setColumns(20);
        actNb.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        actNb.setRows(5);
        jScrollPane6.setViewportView(actNb);

        Inquery.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 56, 580, 100));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane7.setViewportView(jTextArea3);

        Inquery.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1875, 49, -1, -1));

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane8.setViewportView(jTextArea4);

        Inquery.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1199, 49, -1, -1));

        getContentPane().add(Inquery, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed
int cardNumber1;
SqlQueries sql=new SqlQueries();
    private void enterbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterbuttonActionPerformed
        // TODO add your handling code here
        //getCard number from data base if match then enable
        
        cardNumber1=Integer.parseInt(cardNumber.getText());//card from user
        
        
        try {
            sql.databaseConnection();
            if( sql.checkRecord(cardNumber1)){
                
                cardNumber.setEditable(false);
                Pinfield.setEditable(true);
                enterpin.setVisible(true);
                pincontinue.setEnabled(true);
     
                inqueryText.append("\t************************************* WELCOME "+sql.getName(cardNumber1)
                        + " TO HBL ATM **********************"
             + "****************"); }
            else{
           inqueryText.append("\t************************************* INVALID CARD NUMBER TRY AGAIN *****************************"
                   + "*********");
//            cardNumber.setText("Invalid");
            }
            
             
             
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
         
  
    }//GEN-LAST:event_enterbuttonActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
       String number=cardNumber.getText()+"1";
       cardNumber.setText(number);
       
    }//GEN-LAST:event_oneActionPerformed

    private void cardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberActionPerformed

    private void receipt_transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receipt_transferActionPerformed
        // TODO add your handling code here:


       float amount=(float)Integer.parseInt(transfer_amount_field.getText());
       String account=transfer_acount_field.getText();
       
        Calendar timer=Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat t = new SimpleDateFormat("HH:mm:ss");
        t.format(timer.getTime());
        SimpleDateFormat d = new SimpleDateFormat("dd-MMM-yyyy");
        t.format(timer.getTime());
     try {    
    if(amount<=0){
         transferfield.append("\nEnter valid amount\n");}
    else if(amount>50000){
         transferfield.append("\nyour account range not greater then 50k!Try again\n");}
    
    else if(amount>sql.getCurrentBalance(cardNumber1)){
            transferfield.append("\nInsaficient Balance\n");
        }
        else{
        
        if(!sql.checkAccountNumber(account)){
            transferfield.append("\nInvalid Account Number!Try again\n");
        }
        else{
            String a=account;
     
            sql.transfer(cardNumber1,a, amount);
            transferfield.append("\tHBL ATM\n*******************************\n\n"
                + "Transferd Amount=" + amount+"\n"
                        + "Remaing="+sql.getCurrentBalance(cardNumber1)
                        + "\n*******************************\n"
                        + "Date:  "+d.format(timer.getTime())+"\n"
                                + "Time:  "+ t.format(timer.getTime())+"\n"
                                        + "\n Thank You!!");
            receipt_transfer.setEnabled(false);
        }
                  
            
        }
        
        
        
     } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
    }//GEN-LAST:event_receipt_transferActionPerformed

    private void receipt_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receipt_billActionPerformed
        // TODO add your handling code here:
        String billNo=String.format(billno_field.getText());
        String bill=String.format(cBox_bill.getSelectedItem().toString());
        float amount=(float)Integer.parseInt(bill_amount_field.getText());
        
        
        Calendar timer=Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat t = new SimpleDateFormat("HH:mm:ss");
        t.format(timer.getTime());
        SimpleDateFormat d = new SimpleDateFormat("dd-MMM-yyyy");
        t.format(timer.getTime());
        
        try {
            float a=sql.getCurrentBalance(cardNumber1);
            if(a<amount){
                billText.append("Insaficient BAlance");}
            
            else if(a<0){billText.append("Invalid amount");}
            else{
            sql.billPayent(cardNumber1, amount);
            
            try {
            billText.append("\tHBL ATM\n*******************************\n"
                    + "Bill Number =" + billNo+"\nType:"+bill
                    + "\nbill Amount="+amount +" Paid\nremaning in your account="+sql.getCurrentBalance(cardNumber1)
                    + "\n*******************************\n"
                            + "Date:  "+d.format(timer.getTime())+"\n"
                                    + "Time:  "+ t.format(timer.getTime())+"\n"
                                            + "Thank You!!");
        } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        receipt_bill.setEnabled(false);
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_receipt_billActionPerformed

     private JFrame frame;
    private void exit_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_withdrawActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Atm with Exit",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_exit_withdrawActionPerformed

    private void exit_TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_TransferActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Atm with Exit",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);}
    }//GEN-LAST:event_exit_TransferActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        // TODO add your handling code here:

     receiptWithdraw.setEnabled(false);
     exit_withdraw.setEnabled(false);
     reset_withdraw.setEnabled(false);
     receipt_transfer.setEnabled(false);
     reset_transfer.setEnabled(false);
     exit_Transfer.setEnabled(false);
     receipt_bill.setEnabled(false);
     cBox_bill.setEnabled(false);
     
     
     
     
     withdraw.setEnabled(false);
     inquery.setEnabled(false);
     transfer.setEnabled(false);
     billpay.setEnabled(false);
     
     withdrawlable.setVisible(false);
     inquerylable.setVisible(false);
     billplable.setVisible(false);
     Transferlable.setVisible(false);
     enterpin.setVisible(false);
     userAccount.setVisible(false);
     userAmount.setVisible(false);
     
    Pinfield.setEditable(false);
    with_draw_amount_field.setEditable(false);
    transfer_acount_field.setEditable(false);
    transfer_amount_field.setEditable(false);
    billno_field.setEditable(false);
    pincontinue.setEnabled(false);
    pincontinue.setEnabled(false);
    bill_amount_field.setEditable(false);
    inqueryText.setEditable(false);
    
    actNb.setEditable(false);
   
   
    }//GEN-LAST:event_formWindowActivated

    private void inqueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inqueryActionPerformed
        // TODO add your handling code here:
     receipt_transfer.setEnabled(false);
     reset_transfer.setEnabled(false);
     exit_Transfer.setEnabled(false);
     receipt_bill.setEnabled(false);
     cBox_bill.setEnabled(false);
     pincontinue.setEnabled(false);
     bill_amount_field.setEditable(false);
     receiptWithdraw.setEnabled(false);
     exit_withdraw.setEnabled(false);
     reset_withdraw.setEnabled(false);
     
     userAccount.setVisible(true);
     userAmount.setVisible(true);
     float currentBalance=0;
     String accountNumber=null;
     
        try {
            currentBalance=sql.getCurrentBalance(cardNumber1);
            accountNumber=sql.getAccountNumber(cardNumber1);
        } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }   
        actNb.append(" "+accountNumber+"\n\n\n"+currentBalance);  
    }//GEN-LAST:event_inqueryActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        // TODO add your handling code here:
     receipt_transfer.setEnabled(true);
     reset_transfer.setEnabled(true);
     exit_Transfer.setEnabled(true);
     
     receiptWithdraw.setEnabled(false);
     exit_withdraw.setEnabled(false);
     reset_withdraw.setEnabled(false);
     receipt_bill.setEnabled(false);
     cBox_bill.setEnabled(false);
     

       
    transfer_amount_field.setEditable(true);
    transfer_acount_field.setEditable(true);
     pincontinue.setEnabled(false);
     bill_amount_field.setEditable(false);
     bill_amount_field.setEditable(false);
        
    }//GEN-LAST:event_transferActionPerformed

    private void billpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billpayActionPerformed
        // TODO add your handling code here:
     receipt_bill.setEnabled(true);
     cBox_bill.setEnabled(true);
     billno_field.setEditable(true);
     
     receiptWithdraw.setEnabled(false);
     exit_withdraw.setEnabled(false);
     reset_withdraw.setEnabled(false);
     receipt_transfer.setEnabled(false);
     reset_transfer.setEnabled(false);
     exit_Transfer.setEnabled(false);
      pincontinue.setEnabled(false);
      bill_amount_field.setEditable(true);
      bill_amount_field.setEditable(true);

      
    }//GEN-LAST:event_billpayActionPerformed

    private void reset_withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_withdrawActionPerformed
        // TODO add your handling code here:
        with_draw_amount_field.setText(null);
    }//GEN-LAST:event_reset_withdrawActionPerformed

    private void reset_transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_transferActionPerformed
        // TODO add your handling code here:
         transfer_acount_field.setText(null);
         transfer_amount_field.setText(null);
        
    }//GEN-LAST:event_reset_transferActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
         String number=cardNumber.getText()+"2";
       cardNumber.setText(number);
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
         String number=cardNumber.getText()+"3";
       cardNumber.setText(number);
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
         String number=cardNumber.getText()+"4";
       cardNumber.setText(number);
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
         String number=cardNumber.getText()+"5";
       cardNumber.setText(number);
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
         String number=cardNumber.getText()+"6";
       cardNumber.setText(number);
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
         String number=cardNumber.getText()+"7";
       cardNumber.setText(number);
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
         String number=cardNumber.getText()+"8";
       cardNumber.setText(number);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        String number=cardNumber.getText()+"9";
       cardNumber.setText(number);
    }//GEN-LAST:event_nineActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
         String number=cardNumber.getText()+"0";
       cardNumber.setText(number);
    }//GEN-LAST:event_zeroActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        cardNumber.setText(null);
    }//GEN-LAST:event_clearActionPerformed

    private void cancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to Cancle", "Atm with Exit",
               JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }

    }//GEN-LAST:event_cancleActionPerformed

    private void with_draw_amount_fieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_with_draw_amount_fieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_with_draw_amount_fieldKeyTyped
     public int pinn=0;
    private void pincontinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincontinueActionPerformed
        
         int pin1=Integer.parseInt(Pinfield.getText());
         
    try {
            // TODO add your handling code here:
            int a=pin1;
            int pin=sql.getPin(cardNumber1);
            
    if(a==pin){
    cardNumber.setEditable(false);
    Pinfield.setEditable(false);
     withdraw.setEnabled(true);
     inquery.setEnabled(true);
     transfer.setEnabled(true);
     billpay.setEnabled(true);
     withdrawlable.setVisible(true);
     inquerylable.setVisible(true);
     billplable.setVisible(true);
     Transferlable.setVisible(true);
      pincontinue.setEnabled(false); }
    else{
           inqueryText.append("\t************************************* INVALID Pin TRY AGAIN *****************************"
                   + "*********");

            }
    
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
                
         
    }//GEN-LAST:event_pincontinueActionPerformed

    private void receiptWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptWithdrawActionPerformed
        // TODO add your handling code here:
        
        
        float amount=(float)Integer.parseInt(with_draw_amount_field.getText());
        Calendar timer=Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat t = new SimpleDateFormat("HH:mm:ss");
        t.format(timer.getTime());
        SimpleDateFormat d = new SimpleDateFormat("dd-MMM-yyyy");
        t.format(timer.getTime());
     try {    
    if(amount<=0){
         text_withdraw.append("\nenter valid amount\n");}
    else if(amount>50000){
         text_withdraw.append("\nyour account range not greater then 50k!Try again\n");}
    
    else if(amount>sql.getCurrentBalance(cardNumber1)){
            text_withdraw.append("\nInsaficient Balance\n");
        }
        else{
            sql.withdrawAmount(cardNumber1, amount);
            text_withdraw.append("\tHBL ATM\n*******************************\n\n"
                + "Withdraw Amount=" + amount+"\n"
                        + "Remaing="+sql.getCurrentBalance(cardNumber1)
                        + "\n*******************************\n"
                        + "Date:  "+d.format(timer.getTime())+"\n"
                                + "Time:  "+ t.format(timer.getTime())+"\n"
                                        + "\n Thank You!!");
            receiptWithdraw.setEnabled(false);
            
        }
        
        
        
     } catch (SQLException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
        
          
    }//GEN-LAST:event_receiptWithdrawActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void withdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawActionPerformed
        receiptWithdraw.setEnabled(true);
        exit_withdraw.setEnabled(true);
        reset_withdraw.setEnabled(true);
        with_draw_amount_field.setEditable(true);

        receipt_transfer.setEnabled(false);
        reset_transfer.setEnabled(false);
        exit_Transfer.setEnabled(false);
        receipt_bill.setEnabled(false);
        cBox_bill.setEnabled(false);
        pincontinue.setEnabled(false);
        bill_amount_field.setEditable(false);

    }//GEN-LAST:event_withdrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inquery;
    private javax.swing.JTextField Pinfield;
    private javax.swing.JPanel Transfer;
    private javax.swing.JLabel Transferlable;
    private javax.swing.JLabel accountnumberlable_transfer;
    private javax.swing.JTextArea actNb;
    private javax.swing.JLabel amountlable_transfer;
    private javax.swing.JLabel amountlable_withdraw;
    private javax.swing.JPanel bill;
    private javax.swing.JTextArea billText;
    private javax.swing.JTextField bill_amount_field;
    private javax.swing.JLabel bill_lable;
    private javax.swing.JTextField billno_field;
    private javax.swing.JButton billpay;
    private javax.swing.JLabel billplable;
    private javax.swing.JLabel billtype_lable;
    private javax.swing.JLabel billtype_lable1;
    private javax.swing.JComboBox<String> cBox_bill;
    private javax.swing.JButton cancle;
    private javax.swing.JTextField cardNumber;
    private javax.swing.JButton clear;
    private javax.swing.JButton eight;
    private javax.swing.JButton enterbutton;
    private javax.swing.JLabel enterpin;
    private javax.swing.JButton exit_Transfer;
    private javax.swing.JButton exit_withdraw;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton inquery;
    private javax.swing.JTextArea inqueryText;
    private javax.swing.JLabel inquerylable;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton pincontinue;
    private javax.swing.JButton receiptWithdraw;
    private javax.swing.JButton receipt_bill;
    private javax.swing.JButton receipt_transfer;
    private javax.swing.JButton reset_transfer;
    private javax.swing.JButton reset_withdraw;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JTextArea text_withdraw;
    private javax.swing.JButton three;
    private javax.swing.JButton transfer;
    private javax.swing.JTextField transfer_acount_field;
    private javax.swing.JTextField transfer_amount_field;
    private javax.swing.JTextArea transferfield;
    private javax.swing.JButton two;
    private javax.swing.JLabel userAccount;
    private javax.swing.JLabel userAmount;
    private javax.swing.JTextField with_draw_amount_field;
    private javax.swing.JButton withdraw;
    private javax.swing.JLabel withdrawlable;
    private javax.swing.JPanel withdrawpanel;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
